name: gh-pages

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: build gh pages
    runs-on: ubuntu-latest
    env:
      TARGET: no-modules

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: install puppeteer
        run: yarn install

      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: build
        run: make gh-pages/build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
