name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-web:
    name: test in browser
    uses: lib-ruby-parser/wasm-bindings/.github/workflows/shared-build-and-test.yml@master
    with:
      node: '15'
      target: no-modules
      env: web

  test-node:
    name: test with node
    uses: lib-ruby-parser/wasm-bindings/.github/workflows/shared-build-and-test.yml@master
    with:
      node: '15'
      target: nodejs
      env: nodejs
